services:
  restapi:
    build:
      context: .
      dockerfile: Platform.RestApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80

  webclient:
    build:
      context: .
      dockerfile: Platform.WebClient/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DocuwareClient__BaseUrl=http://restapi
      - DocuwareClient__Username=platform-client
      - DocuwareClient__Password=password
    depends_on:
      - restapi

  thirdparty:
    build:
      context: .
      dockerfile: ThirdParty.Consumer/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DocuwareClient__BaseUrl=http://restapi
      - DocuwareClient__Username=platform-client
      - DocuwareClient__Password=password
    depends_on:
      - restapi
